---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```



# 75 Soft: 75 Days of software development

Viral 75-day challenges are out there to develop your physical & entrepreneurial prowess, but none seek to grow mental toughness through consistency & discipline as a software developer. This talk provides a short history of these development experiments & acknowledges the potential upside if applied in the right context: enter "75 Soft for Software Devs". The talk will layout a checklist of tasks to follow each day to improve your overall confidence and appetite to learn. But don't miss a task, otherwise you'll have to start over from day 1. You'll leave the talk with first-hand advice from those who've attempted such a feat and even a personal invitation to join in a community-based 75-day attempt for yourselves! Just think, you can finally get to all those bookmarks you've saved from past conferences (and this one too). You could commit to ingesting a trendy new package or finally transitioning from Rmd to Quarto. Don't limit yourself - it's time to get soft!



## Does this ever happen to you?





## 75 What?

	1. Follow a diet
	2. 2 x 45 minute workouts (one has to be outside)
	3. Drink 1 Gallon of Water
	4. Read 10 pages of non-fiction (personal dev, no audiobooks)
  5. Take progress pictures
  
  
  
## 75 When?

Every. single. day.
  
  
  
## 75 Why?

Because fire refines. Obstacles and hurdles are what it takes to learn, grow, and conquer which ultimately lead to confidence & grit. The program exists to produce software developers who are mentally tough. The creators of "75 Had" call it an "Ironman for your brain".



## 75 Who?

2M+ have attempted it, and only 5% (~100,000) from all over the world have successfully reached the finished line.



## 75 How?

5 tasks per day, nothing more or nothing less. 5 because that allows you to "win the day" and generate more confidence in yourself.
	- If it's more than 5, you won't have a life and you'll be a work-aholic
	- If it's less than 5, it's not challenging to finish, so you won't grow

Don't change the recipe! If Julia Childs made this recipe and it's award winning. It's worked for everyone else, why won't it work for you? Don't change the recipe.



## 75 me?

What would that look like? Think of all the improvement you could realize - what does the best version of me as a disciplined programmer?



## The 75 Soft checklist for software dev dev

1. Devour one learning resource you've been wanting to consume
2. Contribute on two projects (one has to be open source)
3. Watercooler - share your learnings on social media
4. Read 10 pages of a software dev book
5. Track your progress in Quarto/ Rmarkdown
  
  
  
### Ground rules

Adherence to the plan is suggested for only business days.



### 1. Follow a diet

We are what we consume, so create a healthy diet by consuming new learning materials every day. That could mean picking a topic from one of the following resources each day:
  - shiny weekly
  - R bloggers
  - go back and watch Conf videos you good intentions to watch
  - tutorials, online courses, or camps
	
	
	
### 2. 2 x 45 minute workouts (one has to be outside)

	- Spend 2x 45 mins contributing code to a project, one has to be open source
		- Find something industry specific - in pharma, we have the pharmaverse!
			- Never worked on a package, then read r-pkgs.org during your 
			
		- Not used to contributing open source, no worries!
			- Start writing that new package you've always wanted to create. I can't tell you what it is, but start a regimen that you can stick to that helps you refine your pkg-writing skills. Don't cheat?...
			
Guess what? These activities require code too:
	- Write a book(down) on your passion
	- Create a presentation for an upcoming conference
	
	
		
### 3. Drink 1 Gallon of Water
	1. Water cooler - network yourself. Post on a social media:
	  - twitter or mastadon
	  - linkedin (don't under-estimate)
	  - instagram, IDC


	
### 4. Read 10 pages of non-fiction (no vids, no blogs, no audiobooks, better your personal dev)
	- The clean coder
	- Clean code
	- The Pragmatic Programmer
	- r-pkgs.org
	- mastering-shiny.org
	- r4ds.had.co.nz
  - R & Javascript
	- [Big book of R](https://www.bigbookofr.com/)
	
	
	
### 5. Take progress pictures
	• Create a journal in a Rmarkdown / bookdown format to write down what you did or learned today
	• Take pics of your green squares


### Inspo

In Jim Collin's book, "Good to Great"", his research team chronicles ~30 companies that went from mediocre (or worse) and launched into long-term sustained success. The single most distinguishing characteristics of these companies: discipline.

  - Disciplined People
  - Disciplined Thought
  - Disciplined Action











<br>
